version: "3.8"

services:
  postgres:
    image: postgres:16.8
    container_name: recetas-db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: recetas-backend
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/app
    
    command: >
      sh -c "
        echo 'Esperando a que Postgres esté arriba…';
        until pg_isready -h postgres -p 5432 -U ${POSTGRES_USER}; do
          sleep 1;
        done;
        echo 'Postgres listo';
        npm install;
        npx drizzle-kit push;
        npm run run:triggers;
        npm run dev;
      "
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: recetas-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend

volumes:
  db_data: